# Generated by Django 4.2.3 on 2023-07-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_cliente_alter_libros_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('Free', 'Free')], max_length=50)),
                ('fechaInicio', models.DateField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Membresia',
        ),
    ]
