# Generated by Django 4.2.3 on 2023-07-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_cliente_fechainicio_cliente_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fechaInicio',
        ),
    ]
